version: '3.5'
services:
  charashee:
    image: p20/charashee:v0.3
    container_name: charashee
    volumes:
      - './src/charashee/:/src/charashee'
      - './etc/letsencrypt:/etc/letsencrypt'
    environment:
      WSOCKET_PORT: 8899
      SERVER_PORT: 80
      CERT_PATH: /etc/letsencrypt/live/gnosco.net
    ports:
      - '8899:8899'
    tty: true
    stdin_open: true
