version: '3.5'
services:
  charashee:
    image: p20/charashee:v0.3
    container_name: charashee
    volumes:
      - './src/charashee/:/src/charashee'
    environment:
      WSOCKET_PORT: 2883
      SERVER_PORT: 80
    ports:
      - '2883:2883'
      - '80:80'
    tty: true
    stdin_open: true
